apiVersion: v1
kind: Service
metadata:
  name: leptos-cv-svc
  namespace: houston-cv
  labels:
    app: leptos-cv
spec:
  type: ClusterIP
  selector:
    app: leptos-cv
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
