apiVersion: apps/v1
kind: Deployment
metadata:
  name: leptos-cv
  namespace: houston-cv
spec:
  template:
    spec:
      containers:
        - name: leptos-cv
          imagePullPolicy: Never
          env:
            - name: SURREAL_PASS
              value: "root"
              valueFrom: null
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "100m"
