apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: houston-cv
spec:
  template:
    spec:
      containers:
        - name: ollama
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"
