apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: surrealdb
  namespace: houston-cv
spec:
  volumeClaimTemplates: []
  template:
    spec:
      containers:
        - name: surrealdb
          imagePullPolicy: Never
          env:
            - name: SURREAL_PASS
              value: "root"
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          volumeMounts:
            - name: surrealdb-data
              mountPath: /data
      volumes:
        - name: surrealdb-data
          emptyDir: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: surrealdb-init
  namespace: houston-cv
spec:
  template:
    spec:
      containers:
        - name: surrealdb-init
          imagePullPolicy: Never
