apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: houston-cv

resources:
  - namespace.yaml
  - leptos-cv/
  - surrealdb/
  - phoenix-dashboard/
  - ollama/
  - searxng/
  - ingress/
